name = "Portfolio"
license = "MIT"
description = "Minimal portfolio theme for GitHub Pages"
homepage = "https://github.com/dottorconti/dottorconti.github.io"
min_version = "0.100.0"

[author]
  name = "Dottorconti"
  homepage = "https://dottorconti.github.io"
